import { getAppBaseUrl } from "@/lib/db";
import type { Asset, Layer, Scene, Streamer, WorkspaceSnapshot } from "@/lib/types";

const streamer: Streamer = {
  id: "mock-streamer-1",
  name: "Streamer 1",
  handle: "nome do streamer",
  streamKey: "streamer-1",
  activeSceneId: "mock-scene-1",
};

const activeScene: Scene = {
  id: "mock-scene-1",
  streamerId: streamer.id,
  name: "Pagina 1",
  width: 1920,
  height: 1080,
  background: "#0b0b0c",
  status: "live",
};

const assets: Asset[] = [
  {
    id: "mock-asset-title",
    streamerId: streamer.id,
    name: "Titulo da live",
    kind: "text",
    mimeType: "text/plain",
    storageUrl: null,
    thumbnailUrl: null,
    sizeBytes: null,
    durationMs: null,
    metadata: { fontFamily: "JetBrains Mono NFP" },
    createdBy: "moderator",
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "mock-asset-frame",
    streamerId: streamer.id,
    name: "Frame principal",
    kind: "frame",
    mimeType: null,
    storageUrl: null,
    thumbnailUrl: null,
    sizeBytes: null,
    durationMs: null,
    metadata: { border: "solid" },
    createdBy: "moderator",
    createdAt: new Date(0).toISOString(),
  },
];

const layers: Layer[] = [
  {
    id: "mock-layer-1",
    sceneId: activeScene.id,
    parentId: null,
    assetId: "mock-asset-title",
    kind: "text",
    name: "Texto 1",
    orderIndex: 1,
    visible: true,
    locked: false,
    x: 148,
    y: 116,
    width: 420,
    height: 80,
    rotation: 0,
    opacity: 100,
    fill: "#f6dae0",
    content: "[titulo da live]",
    blendMode: "normal",
    metadata: { fontFamily: "JetBrains Mono NFP", fontSize: 42, fontWeight: 700 },
  },
  {
    id: "mock-layer-2",
    sceneId: activeScene.id,
    parentId: null,
    assetId: null,
    kind: "text",
    name: "Texto 2",
    orderIndex: 2,
    visible: true,
    locked: false,
    x: 148,
    y: 206,
    width: 380,
    height: 56,
    rotation: 0,
    opacity: 100,
    fill: "#9a4059",
    content: "@[nome do streamer]",
    blendMode: "normal",
    metadata: { fontFamily: "JetBrains Mono NFP", fontSize: 24, fontWeight: 500 },
  },
  {
    id: "mock-layer-3",
    sceneId: activeScene.id,
    parentId: null,
    assetId: "mock-asset-frame",
    kind: "frame",
    name: "Frame 1",
    orderIndex: 3,
    visible: true,
    locked: false,
    x: 704,
    y: 184,
    width: 520,
    height: 300,
    rotation: 0,
    opacity: 100,
    fill: "#9a4059",
    content: "",
    blendMode: "normal",
    metadata: { radius: 12, strokeWidth: 3 },
  },
];

export function getMockWorkspace(message = "Neon ainda nao foi configurado; exibindo dados locais de desenvolvimento."): WorkspaceSnapshot {
  return {
    streamer,
    scenes: [activeScene],
    activeScene,
    layers,
    assets,
    database: {
      connected: false,
      source: "mock",
      message,
    },
    overlayUrl: `${getAppBaseUrl()}/overlay/${streamer.streamKey}`,
  };
}
